import fs from 'node:fs';
import path from 'node:path';
import { targetRoot } from './target-root.mjs';
const root=targetRoot();
const residents=JSON.parse(fs.readFileSync(path.join(root,'assets/data/habitantes.json'),'utf8'));
const site='https://santuariowinston.org';
const publicRoots=['','habitantes.html','guardianes.html','tienda.html','como-ayudar.html','hazte-socio.html','apadrina.html','teaming.html','donar.html','adopciones-solidarias.html','en-busca-del-paraiso.html','voluntariado.html','testimonios.html','voluntariado-habitual.html','larga-estancia.html','actividades.html','sobre-nosotros.html','transparencia.html','contacto.html','politica-de-privacidad.html'];
const urls=[...publicRoots.map(p=>`${site}/${p}`),...residents.map(r=>`${site}/animales/${r.slug}/`)];
const xml=`<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${urls.map(url=>`  <url><loc>${url}</loc></url>`).join('\n')}\n</urlset>\n`;
fs.writeFileSync(path.join(root,'sitemap.xml'),xml,'utf8');
console.log(`Sitemap generado: ${urls.length} URLs.`);
