import { spawnSync } from 'node:child_process';
const production=process.env.WINSTON_PRODUCTION==='1';
const run=(script)=>{const result=spawnSync(process.execPath,[script],{stdio:'inherit',env:process.env});if(result.status!==0)process.exit(result.status??1);};
run('scripts/extract-habitantes.mjs');
run('scripts/sync-public-content.mjs');
run('scripts/update-habitantes-directory.mjs');
run('scripts/build-storefront.mjs');
run('scripts/build-transparency.mjs');
run('scripts/update-storefront-links.mjs');
run('scripts/update-transparency-links.mjs');
run('scripts/update-public-shell.mjs');
run('scripts/build-habitantes.mjs');
run('scripts/build-content.mjs');
run('scripts/build-winston-knowledge.mjs');
run('scripts/update-public-domain.mjs');
run('scripts/normalize-public-html.mjs');
run('scripts/apply-seo.mjs');
run('scripts/apply-structured-data.mjs');
run('scripts/apply-performance.mjs');
run('scripts/apply-accessibility.mjs');
run('scripts/build-404.mjs');
run('scripts/build-sitemap.mjs');
run('scripts/set-indexing.mjs');
run('scripts/build-cloudflare-config.mjs');
run('scripts/apply-analytics.mjs');
console.log(`Build público completo (${production?'producción':'staging'}).`);
